### ISSUE TITLE
[Nice Change] Alphabetic order readme

### ISSUE THREAD

**Issue by Mastergamer433** [Jontes-Tech/searchofchoice#1]
This is not nessecary but i just think its nicer.

The "Supported Search Engines" section of the readme.md isn't in alphabetic order.

I wanna fix it.

**Comment by Jontes-Tech** [comment]
I see that you created PR #2. The reason that they are not in an aplhabetic order is because it's according to their ids (the string stored in cookies, see [script.js](https://github.com/Jontes-Tech/searchofchoice/blob/main/script.js). I might actually sort them in the alphabetical order, but in the time I've been considering this change (the last 24 days or so) the readme has changed, so I the reordering would have to happen again with another commit to your PR. If you want to I will happily do it myself but you are free to if you want to (thanks for your patience, I've been really busy so sorry for late reply)

**Comment by Jontes-Tech** [comment]
Closing
